name: rick_and_morty
description: lemon hive assessment
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.3
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  gradient_borders: ^1.0.0
  internet_connection_checker_plus: ^2.2.0
  flutter_bloc: ^8.1.4
  google_fonts: ^6.2.1
  dio: ^5.4.1
  sqflite: ^2.3.2
  get_it: ^7.6.7
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.4
  dropdown_search: ^5.0.6
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  lottie: ^3.0.0
  flutter_screenutil: ^5.9.0
  
dev_dependencies:
  bloc_test: ^9.1.6
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  #very_good_analysis: ^5.1.0

flutter_gen:
  # Optional
  output: lib/gen/
  # Optional
  line_length: 80

  # Optional
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false
    
  colors:
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: AppColors      

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
